from .dr_science import *
from .elon import *
from .elon2 import *
from .cpp_coding import *
from .react_template import *
from .rewoo_template import *
from .openai_template import *
from .vanilla_template import *
from .openai_memory_template import *
from .vanilla-ziyu import *
from .scholar-ziyu import *
from .Captain_America import *
from .scholar_agent import *
from .google_search import *
from .google_search_agent import *
from .pdf_google_agent import *
from .Career_Advisor import *
from .Geometry_Calculator import *
from .vanilla_agent import *
